retail <- read.csv("RetailData.csv", skip=2) [,23]
retailts <- (ts(retail, frequency=12, start=c(1982,4)))
plot(retailts, xlim=(c(1982,2015)))
retailfit <- snaive(retailts, h=3)
plot(retailfit, plot.conf=FALSE, main="Forecasts for monthly retail sales")
lines(retailfit$mean,col="red")
pdf("Forecasts for monthly retail sales.pdf")
plot(retailfit, plot.conf=FALSE, main="Forecasts for monthly retail sales")
lines(retailfit$mean,col="red")
dev.off()